name = 'duke nukem'
position = 3

[[sound]]
name = 'Balls of steel'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54065', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Balls'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54066', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Steel'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54067', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Have A Taste of My Ball'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=893187', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''Looks Like You're F'd'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=893190', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''I'm Gonna Kill You Old Style'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=893189', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'You Can See My D*ck From Here'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=893188', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''I'm an equal opportunity ass kicker'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75556', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''You're an inspiration for birth control'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54068', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'I oughta break a broomhandle off in your ass'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75553', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''Damn, you're ugly'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54069', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''You're gonna die for that'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54070', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Rest in pieces'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75561', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Wasted!'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54072', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''I'm gonna kick your ass, bitch!'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54073', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Blow it out your ass!'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54074', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Yippie kai-ay mother f***er!'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54077', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''Don't get your panties all in a bunch'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75558', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Who wants some?'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54078', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Come get some!'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54079', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'This is KTIT...'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54081', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Damn, that was annoying.'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54082', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''Damn, I'm good.'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54083', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Quit wasting my time'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75560', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''My name's Duke Nukem'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54084', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'This really pisses me off'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54085', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''You're pissin me off'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54086', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''Now I'm really pissed off'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75557', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Get back to work, you slacker!'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54087', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''Looks like it's time for me to go postal'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54088', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''I'll rip your head off and shit down your neck'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54089', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Go ahead, make my day'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54090', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''I'm gonna get medieval on your asses'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54091', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''Don't have time to play with myself'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54092', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'See you in hell'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54093', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''It's time to kick ass and chew bubblegum...'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54094', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'You guys suck'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54095', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Hail to the king, baby!'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54096', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'I like big guns...'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75562', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''It's my way or...'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75564', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Shit happens'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54097', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '*sniff*  Something smells rotten...'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75566', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Die, you S.O.B.!'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54099', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Eat shit and die'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54100', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''Your face, your ass, what's the difference?'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54101', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''My gun's bigger than yours'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75565', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Say hello to my little friend'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75563', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Get that crap outta here'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54102', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Game over!'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54103', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Son of a bitch!'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75567', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''Ooooh, that's gotta hurt.'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54104', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Holy cow'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54105', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'Holy shit!'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54106', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''Let God sort 'em out!'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54107', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = '''What, there's only one of you?'''
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54108', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'It hurts to be you'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=54345', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

[[sound]]
name = 'You talkin to me?'
source = {http = {url = 'https://www.soundboard.com/handler/playTrack.ashx?id=75559', headers = [{name = 'referer', value = 'https://www.soundboard.com/'}]}}

